export const heroes = [
  {
    id: 1,
    name: "Alencia",
    rarity: 5,
    element: "earth",
    role: "Warrior",
    getIcon() {
      return `assets/${this.name.replaceAll(" ", "-")}-icon.png`;
    },
  },
  {
    id: 2,
    name: "Tywin Ambicioso",
    rarity: 5,
    element: "light",
    role: "Knight",
    getIcon() {
      return `assets/${this.name.replaceAll(" ", "-")}-icon.png`;
    },
  },
  {
    id: 3,
    name: "Ravi Apocalíptica",
    rarity: 5,
    element: "dark",
    role: "Warrior",
  },
  {
    id: 4,
    name: "Araminta",
    rarity: 5,
    element: "fire",
    role: "Mage",
  },
  {
    id: 5,
    name: "Árbitro Vildred",
    rarity: 5,
    element: "dark",
    role: "Thief",
  },
  {
    id: 6,
    name: "Sombra do Arquidemônio",
    rarity: 5,
    element: "dark",
    role: "Mage",
  },
  {
    id: 7,
    name: "Baal e Sezan",
    rarity: 5,
    element: "fire",
    role: "Mage",
  },
  {
    id: 8,
    name: "Baiken",
    rarity: 5,
    element: "earth",
    role: "Thief",
  },
  {
    id: 9,
    name: "Bassar",
    rarity: 5,
    element: "earth",
    role: "Mage",
  },
  {
    id: 10,
    name: "Bellona",
    rarity: 5,
    element: "earth",
    role: "Ranger",
  },
  {
    id: 11,
    name: "Presto da Lua Sangrenta",
    rarity: 5,
    element: "dark",
    role: "Soul Weaver",
  },
  {
    id: 12,
    name: "Modelo Bombardeio Kanna",
    rarity: 5,
    element: "fire",
    role: "Ranger",
  },
  {
    id: 13,
    name: "Bruxa do Espinheiro Iséria",
    rarity: 5,
    element: "dark",
    role: "Ranger",
  },
  {
    id: 14,
    name: "Cecília",
    rarity: 5,
    element: "fire",
    role: "Knight",
  },
  {
    id: 15,
    name: "Celine",
    rarity: 5,
    element: "earth",
    role: "Thief",
  },
  {
    id: 16,
    name: "Cerise",
    rarity: 5,
    element: "ice",
    role: "Ranger",
  },
  {
    id: 17,
    name: "Cérmia",
    rarity: 5,
    element: "fire",
    role: "Warrior",
  },
  {
    id: 18,
    name: "Charles",
    rarity: 5,
    element: "earth",
    role: "Knight",
  },
  {
    id: 19,
    name: "Charlotte",
    rarity: 5,
    element: "fire",
    role: "Warrior",
  },
  {
    id: 20,
    name: "Chloe",
    rarity: 5,
    element: "ice",
    role: "Warrior",
  },
  {
    id: 21,
    name: "Choux",
    rarity: 5,
    element: "ice",
    role: "Warrior",
  },
  {
    id: 22,
    name: "Corvus das Trevas",
    rarity: 5,
    element: "dark",
    role: "Warrior",
  },
  {
    id: 23,
    name: "Jóia do Deserto Bassar",
    rarity: 5,
    element: "light",
    role: "Soul Weaver",
  },
  {
    id: 24,
    name: "Lilibete Estilista",
    rarity: 5,
    element: "dark",
    role: "Warrior",
  },
  {
    id: 25,
    name: "Destina",
    rarity: 5,
    element: "earth",
    role: "Soul Weaver",
  },
  {
    id: 26,
    name: "Diene",
    rarity: 5,
    element: "ice",
    role: "Soul Weaver",
  },
  {
    id: 27,
    name: "Dizzy",
    rarity: 5,
    element: "ice",
    role: "Mage",
  },
  {
    id: 28,
    name: "Eda",
    rarity: 5,
    element: "ice",
    role: "Mage",
  },
  {
    id: 29,
    name: "Elena",
    rarity: 5,
    element: "ice",
    role: "Soul Weaver",
  },
  {
    id: 30,
    name: "Elphelt",
    rarity: 5,
    element: "fire",
    role: "Ranger",
  },
  {
    id: 31,
    name: "Ervalen",
    rarity: 5,
    element: "earth",
    role: "Thief",
  },
  {
    id: 32,
    name: "Tenébria das Fábulas",
    rarity: 5,
    element: "ice",
    role: "Mage",
  },
  {
    id: 33,
    name: "Lidica Infiel",
    rarity: 5,
    element: "light",
    role: "Ranger",
  },
  {
    id: 34,
    name: "Cecília Caída",
    rarity: 5,
    element: "dark",
    role: "Knight",
  },
  {
    id: 35,
    name: "Flan",
    rarity: 5,
    element: "ice",
    role: "Ranger",
  },
];
